# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e117281b2d7c3283d2eb3f45e82aa66555da16177de869ca02c3efd3a2cd239ecf284e22eec4b4cc49c85e49f02edd42b5308fd3aff10d11f2082572ffb8ce2

test:
  secret_key_base: fc6430bf0327ee8607dcdedeb82e8da4f2d2dc8f4413e58c83497a8ffe311eacd93d92b05d12a57c8148cb74fe65f1485b5503a7ddf85dbb424c19b8f7991794

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
